### PR TITLE
socket module replaced with tcp and udp modules

### PR DESCRIPTION
**Pull request by MohamedSabthar**

### CODE REVIEW

**Comment by Maninda** [comment]
@MohamedSabthar, we have to add the entries in the `release/resources/stdlib_modules.json` and `release/resources/module_list.json` for enabling the build pipeline with new module changes.

**Comment by MohamedSabthar** [comment]
> @MohamedSabthar, we have to add the entries in the `release/resources/stdlib_modules.json` and `release/resources/module_list.json` for enabling the build pipeline with new module changes.

 build pipeline enabled with new module changes

**Comment by niveathika** [comment]
@MohamedSabthar Let's change these in the distribution build too

**Review by Maninda — APPROVED** [review]

**Comment by ThisaruGuruge** [comment]
> @MohamedSabthar, we have to add the entries in the `release/resources/stdlib_modules.json` and `release/resources/module_list.json` for enabling the build pipeline with new module changes.

Even though it is not wrong, we don't have to change anything but the `module_list.json` file. All the others are meant to be auto-generated.

**Pull request merged**
