### PR TITLE
Remove filepath module from build pipeline

### PR DESCRIPTION
**Pull request by ThishaniLucas**
$subject

### CODE REVIEW

**Comment by niveathika** [comment]
@ThishaniLucas Shall we update the dashboard table too?

**Comment by ThishaniLucas** [comment]
Seems like it's going to be automated in a couple of days. @ThisaruGuruge

**Comment by ThisaruGuruge** [comment]
> Seems like it's going to be automated in a couple of days. Already discussed with @ThisaruGuruge

Yes, it is already in the review state. Most probably we can have it by end of this week. Shall we keep this as it is until then? We might use this as a test for that functionality as well.

**Review by ThisaruGuruge — APPROVED** [review]
LGTM

**Pull request merged**
